steps:
# Install dependencies
- name: node
  entrypoint: yarn
  args: ['install']
# Run tests
# - name: node
#   entrypoint: yarn
#   args: ['test']
# Run custom commands
- name: node
  entrypoint: node
  args: ['server']